### ISSUE TITLE
[NEW] Search Frequency Rank vs Search Query Volume model initialization project

### ISSUE THREAD

**Issue by beaioun** [Bayland-Health/bayland-models#1]
**What is the model trying to predict/map relationships/classify?**
 We are trying to find the relationship between where x = search frequency rank and y = search query volume to predict the y value with any given x belonging to N in [0, 10^7] on some particular given dates ( the date and seasonal trend is not heavily weighted dimension)

**What is the context for building this model?**
We want to know the relationship between these two variables mainly to pave the way for future analytics and trend prediction to quantify previous changes in rank and translate that change to search query. We almost certainly know that the actual trend is strongly linearly correlated with the search query volume. However, we cannot get access to daily search volume data but we have daily updated search rank data. With this model, we can actually quantify the trend and use the changes in ranking to predict the magnitude of differences in search volume.

**What are the plans or phases for building and deployment?**

**Is this proposed model related to any other models or applications?**
- [ ] Yes this model is related to other models and applications
List here:

**Comment by beaioun** [comment]
@krischenyt I managed to narrow down the dataset by removing the outliers that deviate too much from the polynomial degree 4 model and here is the result:
![image](https://github.com/Bayland-Health/bayland-models/assets/94433735/c9202672-7dfa-4f24-b123-3b50f018d879)
<html>
<body>
<table>

Degree | Mean Squared Error (MSE) | R² Score
-- | -- | --
2 | 18,663,800 | 0.8216
3 | 10,258,550 | 0.9020
4 | 7,287,758 | 0.9304
5 | 38,867,400 | 0.6286
6 | 50,187,190 | 0.5204

</table>
</body>
</html>

I think the polynomial degree 4 model now looks really of promising for x <= 40000
**The narrowed dataset:** [refined_search_data.csv](https://github.com/Bayland-Health/bayland-models/files/13384748/refined_search_data.csv)

**Comment by beaioun** [comment]
@krischenyt more tests needs to be performed on more datasets to be eligible being a stable version of the model

**Comment by krischenyt** [comment]
> @krischenyt more tests needs to be performed on more datasets to be eligible being a stable version of the model

Maybe we can try XGBoost to fit this data set. The result is better than Poly Model.

![download](https://github.com/Bayland-Health/bayland-models/assets/90855897/ca4521b0-5b75-47be-b8c8-55638383ac17)

**Comment by beaioun** [comment]
> > @krischenyt more tests needs to be performed on more datasets to be eligible being a stable version of the model
> 
> Maybe we can try XGBoost to fit this data set. The result is better than Poly Model.
> 
> ![download](https://user-images.githubusercontent.com/90855897/283617134-ca4521b0-5b75-47be-b8c8-55638383ac17.png)

This looks very promising, we may need to smoothen the curve a little bit.

**Comment by beaioun** [comment]
@krischenyt Can we fit a spline based on the predicted datapoints?
Here is how it looks in scatterplot:
![image](https://github.com/Bayland-Health/bayland-models/assets/94433735/fce47033-0b2b-4a75-8905-1a7d2d6ee693)

 **Since the predicted distribution is already pretty tight, we have the following options:**
1. fitting spline over this distribution will help smoothing.
2. fitting the data again with xgboost regressor.
3. this is good enough to use, we can just leave it.

**Comment by beaioun** [comment]
@krischenyt There still is some problem before deployment, since we do not have a continuous model, for all the ranks we can only get output on certain points. 
```
n_array = np.arange(50001)
n_2d_array = n_array.reshape(len(n_array), 1)

plt.scatter(X, y, s=1)
plt.scatter(n_2d_array, xgb_model.predict(n_2d_array), color = 'red', s=1)
plt.xlabel('Ranking')
plt.ylabel('Search Voulme')
# Show the plot
plt.show()
```
![image](https://github.com/Bayland-Health/bayland-models/assets/94433735/62f321ff-8332-48a0-adee-76df851c6a04)

As you can see, many of the horizontal lines that the model produced are not true to the actual distribution. Because we the model doesn't have a prediction for all the X in the range, the model will reference the neighbouring values.

**Comment by beaioun** [comment]
![image](https://github.com/Bayland-Health/bayland-models/assets/94433735/7ecebb74-2e0d-43a5-9785-a08d04b22d6c)
@krischenyt After trying to fit another polynomial regression, I feel like it preserves a good amount of the shape for a rank less than 30000. Let's stitch that with a linear regression from the 30,000+ range and test out the performance on Monday.

**Comment by beaioun** [comment]
@krischenyt 
![image](https://github.com/Bayland-Health/bayland-models/assets/94433735/8e4dbcfa-c092-4e97-93ee-3a2308ebe361)
I think it is pretty effective to split into segments and piece up a model. This is what it looks like using linear for 1-1000, polynomial degree 4 for 1000-30000, polynomial degree 3 for 30000-100000, and another polynomial degree 3 for 100000 onward.

To combine the 4 segments,  we can go ahead and approximate the intersections between models, and use those intersection points to stitch them together.

<html>
<body>
<table>

Model Name | Color | Score
 -- | -- | --
Linear Model | Red | 0.663498
Polynomial Model | Green | 0.779268
Polynomial Model 2 | Yellow | 0.747067
Polynomial Model 3 | Purple | 0.854657

</table>
</body>
</html>

Something we can do to improve this is to use xgboost on the 1000-30000 interval get the projected array and use it to fit an even tighter polynomial model on this segment.

**Comment by beaioun** [comment]
@krischenyt 
![image](https://github.com/Bayland-Health/bayland-models/assets/94433735/c58def20-212a-4231-a97c-cf432bbba117)
****This is a preproduction version of the model, this graph is the line in comparison to the original dataset,**** 
![image](https://github.com/Bayland-Health/bayland-models/assets/94433735/7b6a3b22-e5ca-4af6-9ee3-9882ddd8dbd9)
This graph is the line in comparison to the cleaned dataset, since cleaned dataset is what we will be hope getting in the future, we will use this for benchmarking:
![image](https://github.com/Bayland-Health/bayland-models/assets/94433735/808a4635-e75e-4ce1-ad93-43e08b7a190f)
What we got is an overall R^2 of **0.8977**
I think the unified model is ready for production uses, but I look forward to your take on this.

**Comment by krischenyt** [comment]
I think 0.8977 is good enough for us to utilize this model. We can run this model for multiple weeks to see the outcome. Nice job!
